#ifndef OUTLANDS_GLOBALS_H_
#define OUTLANDS_GLOBALS_H_

#include <stdbool.h>

#define DEFAULT_TARGET_FPS 60
#define DEFAULT_SCREEN_WIDTH 1600
#define DEFAULT_SCREEN_HEIGHT 900

#endif // OUTLANDS_GLOBALS_H_
