#ifndef OUTLANDS_GLOBALS_H_
#define OUTLANDS_GLOBALS_H_

#include <stdbool.h>

#define DEFAULT_TARGET_FPS 60
#define DEFAULT_SCREEN_WIDTH 1600
#define DEFAULT_SCREEN_HEIGHT 900

#define GRID_PIX_WIDTH 40
#define GRID_PIX_HEIGHT 40
#define GRIDS_WIDE (DEFAULT_SCREEN_WIDTH / GRID_PIX_WIDTH)
#define GRIDS_TALL (DEFAULT_SCREEN_HEIGHT / GRID_PIX_HEIGHT)

#define NETWORK_HOST "127.0.0.1"
#define NETWORK_PORT 7000
#define CLIENTS_MAX 8

#endif // OUTLANDS_GLOBALS_H_
